config/routes.rb
Rails.application.routes.draw do
  root to: "images#index"
  devise_for :users
  #delete 'images/all', to: 'images#bulk_destroy'
  resources :images do 
    delete :bulk_destroy, on: :collection 
  end 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
    has_one_attached :picture

    # TODO validate the presence of image 
    # validations - ensures that title and created_by are provided and that visibility must be set to either public or private
     validates_presence_of :title, :created_by, :picture
     validates :visibility, :inclusion => { :in => %w(public private), :message => "%{value} must be public or private" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # DATABASE 
  # - The queries are currently written up for SQLite since this in memory database was chosen to quickly get the project up and running
  # - In the future for the sake of scalability I would definitely want to move it to some form of cloud service (Amazon A3, Microsoft, Google)
  # - SQL/noSQL 


  # MODEL VIEW CONTROLLER 
  # - expand on and style the view for easy form submission 
  # - models and controllers are organized in their respective folders 


  # JSON VALIDATION 
  # - Might want to consider adding this feature as well to verify that the response json is valid 


  # API VERSIONING - SERIALIZATION - PAGINATION (look to add)


  # BOTTLENECKS 
  # - issue with how the backend image repository is set up is that it uses storage as a way to store the actual images 
  # - how active storage operates behind the scenes is as follows:
  # 
  # - Submitting a form  
  #   - when we submit a form, Rails processes the form, stores the received file on disk, encodes its location as a key 
  #   - it then references that key in the active_storage_blobs table and creates a new record in the images table 
  #   - finally it associates an image with a Blob through active_storage_attachments 
  #
  # - Retrieving an image  
  #   - one get request turns into three: ActiveStorage::BlobsController and ActiveStorage::DiskController are both involved 
  #   - they are all used to serve up the image and the URL will always be decoupled from its actual location 
  #   - If a cloud service is used: BlobsController will redirect to a correct URL located in the cloud 

  # - given that rendering one attachment results in at least three database queries this might be an issue if we are 
  # - sequentially calling lots of requests 
  
  # - for bulk modifications Active Storage provides a solution as it provides a scope with_attached_picture (or whatever the attachment name is)
  # - which includes the associated blobs - we can put this into practice by changing Image.all to Image.with_attached_picture
  

  # BULK ADDITION 
  # - There is a way to implement bulk adding images by associating each image with multiple pictures 
  # - One line change but the user might want to do something else like sequentially create multiple images posts by uploading a ton of images 
  # - this is currentlly not supported in this application 

     
  # TEST DRIVEN DEVELOPMENT AND RSPEC TESTS 
  # - Test Driven Development and just general best practice to include testing as we go through the API development process 
  # - currently a work in progress, I mostly developed this project using unit testing with the generated ERBs 


  # SEARCH/SELL/BUY IMAGES 
  # - Really interested in developing these functionalities (my original intention of the project) but getting the basic crud/user/permissions 
  #   took a bit longer than I would have liked 


  # Queries 
  # - Idea was to make querying functionality so we could filter based on the title, created_by, content 
  # - also wanted to look into Amazon Rekognition so that I could query based on the contents of the image 
  # - use Rekognition so that when a user first makes a POST request we could parse the image and associate it with some keywords which 
  #   can then be used to query the image 


  # Managing Inventory and Sales 
  # - 


  # GET /images
  # GET /images.json
  def index
    # TODO: create a service constants class and a function for generating queries 
    visible_flag = "public"
    query = "created_by = \"#{current_user.id}\" OR visibility = \"#{visible_flag}\""
    @images = Image.where(query)
  end

  # GET /images/1
  # GET /images/1.json
  def show
    visible_flag = "public"
    query = "created_by = #{current_user.id} OR visibility = \"#{visible_flag}\""
    # design pattern that you can see public images but you cannot modify or delete them 
    @image = Image.where(query).find(params[:id])
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
    @image = Image.find_by(params[:id], created_by: "#{current_user.id}")
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    @image = Image.find_by(params[:id], created_by: "#{current_user.id}")

    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image = Image.find_by(params[:id], created_by: "#{current_user.id}")

    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  # DELETE /images/all
  def bulk_destroy
    # This allows us to remove all entries from the table corresponding to our current user 
    @images = Image.where(created_by: "#{current_user.id}")
    @images.destroy_all
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Images belonging to user were successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      # honestly this function is not really used as we update @image in the functions
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:title, :created_by, :visibility, :content, :picture).merge(created_by: current_user.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_with(model: image, local: true) do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% image.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  
  <div class="field">
    <%= form.label :visibility %>
    <%= form.text_field :visibility %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
  <%= form.label :picture %>
  <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Images</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Created by</th>
      <th>Visibility</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.title %></td>
        <td><%= image.created_by %></td>
        <td><%= image.visibility %></td>
        <td><%= image.content %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <tr>
      <td><%= link_to 'Bulk_destroy', bulk_destroy_images_path, method: :delete, data: { confirm: 'Are you sure?' } %></td> 
    </tr>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<% if !@image.blank? %>
<p>
  <strong>Title:</strong>
  <%= @image.title %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @image.created_by %>
</p>

<p>
  <strong>Visibility:</strong>
  <%= @image.visibility %>
</p>

<p>
  <strong>Content:</strong>
  <%= @image.content %>
</p>

<% if @image.picture.attached? %>
<!-- @post.picture.present? will always return true, use attached? to check presence -->
  <p>
    <strong>Image:</strong>
    <br>
    <%= image_tag @image.picture %>
  </p>
<% end %>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageRepoApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    
    <p class="navbar-text float-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </p>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>